services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myindihome
      MYSQL_USER: developer
      MYSQL_PASSWORD: secretpassword
    ports:
      - "3306:3306"
    volumes:
      - ./.database:/var/lib/mysql
